//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MArc2.rc
//
#define ID_SKIP_DISK                    4
#define IDD_ABOUTBOX                    100
#define IDB_COPIES_IMAGELIST            101
#define IDB_LIGHTBULB                   102
#define IDD_TIP                         103
#define CG_IDS_DIDYOUKNOW               106
#define CG_IDS_FILE_ABSENT              107
#define CG_IDP_FILE_CORRUPT             108
#define IDR_MAINFRAME                   128
#define IDR_FILESTOARC                  129
#define IDB_TREEIMAGELIST               130
#define IDR_FILETOARC_POPUP             131
#define IDR_ROOMS                       132
#define IDR_COPIES                      133
#define IDB_FTOA_IMAGELIST              134
#define IDD_ROOM_PROPERTIES_DIALOG      136
#define IDR_ROOMS_POPUP                 137
#define IDD_PROGRESS_DIALOG             138
#define IDB_TICK                        140
#define IDB_ROOMS_IMAGELIST             141
#define IDD_INS_DISK_DIALOG             142
#define IDR_COPIES_POPUP                143
#define __DUMMY__                       146
#define IDR_MENU__DUMMY__               148
#define IDB_LOGO                        151
#define IDR_LOG                         152
#define IDR_LOG_POPUP                   153
#define IDD_NAG                         154
#define IDR_FILESTOARC_POPUP            155
#define IDR_ROOM_POPUP                  156
#define IDR_COPY_POPUP                  157
#define IDR_MARC2TYPE                   158
#define IDD_REGISTER_DIALOG             159
#define IDR_LOCATOR                     160
#define IDD_LOCATOR_DIALOG              161
#define IDR_LOCATOR_POPUP               162
#define IDR_LOCATOR_EXCL                164
#define IDD_INPUT_STRING_DIALOG         165
#define IDD_OPTIONS_DIALOG              166
#define IDD_FILETOARC_PROPERTIES_DIALOG 169
#define IDB_BITMAP1                     170
#define IDC_ROOMPROP_LIMIT              1000
#define IDC_BULB                        1000
#define IDC_STARTUP                     1001
#define IDC_PROGRESS                    1002
#define IDC_NEXTTIP                     1002
#define IDC_COPYING_LABEL               1003
#define IDC_ANALYSING_BMP               1004
#define IDC_TIPSTRING                   1004
#define IDC_COPYING_BMP                 1005
#define IDC_COPYING_SUCCESS             1006
#define IDC_INS_DISK_LBL                1007
#define IDC_CURRENT_FILENAME            1008
#define IDC_LICENSED_TO                 1009
#define ID_REGISTER                     1010
#define IDC_REGISTER_TEXT               1011
#define IDC_NAME_EDIT                   1012
#define IDC_CODE_EDIT                   1013
#define IDC_DAYS_COUNTER                1014
#define IDC_LOCATOR_START_PATH          1017
#define IDC_LOCATOR_CURRENT_FOLDE       1018
#define IDC_CHECKED_FILES               1019
#define IDC_COUNTER                     1020
#define IDC_LCTR_BROWSE                 1021
#define IDC_LOCATOR_DAYS_SPIN           1023
#define IDC_LOCATOR_DAYS                1024
#define IDC_SKIP_SOME_FILES             1025
#define IDC_EXCL_FILE_TYPES_BUTTON      1027
#define IDC_EXCL_FOLDERS_BUTTON         1028
#define IDC_EDIT                        1028
#define IDR_LOCATOR_EXCL_POPUP          1029
#define IDC_ROOM_COMPRESSION_ALLOWED    1030
#define IDC_ROOM_COMPRESSION_ALWAYS     1031
#define IDC_ROOM_COMPRESSION_NEVER      1032
#define IDC_ROOM_WHEN_USE_COMPRESSION   1033
#define IDC_DEFAULT_NUMBER_OF_COPIES_EDIT 1034
#define IDC_COMPRESSION_UTILITY_COMBO   1035
#define IDC_COMPRESSOR_PATH_EDIT        1036
#define IDC_BROWSE_BUTTON               1037
#define IDC_EDIT_FILENAME               1038
#define IDC_COMPRESS                    1039
#define IDC_EDIT_UPTOCOPIES             1041
#define ID_SHOWTREE                     32778
#define ID_SHOWINFO                     32782
#define ID_FILETOARC_SHOWCOPIES         32784
#define ID_WINDOW_FILESTOARCHIVE        32785
#define ID_ROOM_NEW                     32786
#define ID_ROOM_DELETE                  32788
#define ID_ROOM_PROPERTIES              32790
#define ID_ARCHIVE_UPDATE               32792
#define ID_WINDOW_COPIES                32793
#define ID_COPY_PROPERTIES              32794
#define ID_COPY_DELETE                  32795
#define ID_COPY_EXTRACT                 32799
#define ID_COPIES_THISISCOPIESLIST      32801
#define ID_UPDATE_FILES                 32805
#define ID_SHOW_WINDOW_ROOMS            32806
#define ID_FILETOARC_DELETE             32815
#define ID_VIEW_LOG                     32816
#define ID_LOG_CLEAR                    32818
#define ID_FILETOARC_GO                 32819
#define ID_FILETOARC_PAUSE              32820
#define ID_HELP_TIPOFTHEDAY             32829
#define ID_START_LOCATOR                32831
#define ID_LOCATOR_REMOVE               32833
#define ID_LOCATOR_ADD                  32834
#define ID_LOCATOR_EXCL_ADD             32837
#define ID_LOCATOR_EXCL_REMOVE          32838
#define ID_LOCATOR_EXCL_ACCEPT          32839
#define ID_LOCATOR_EXCL_RESTORE_DEFAULTS 32840
#define ID_FILE_OPTIONS                 32841
#define ID_FILETOARC_PROPERTIES         32842
#define ID_LOCATOR_ADD_EXCL_TYPE        32847
#define ID_LOCATOR_ADD_EXCL_FOLDER      32849
#define ID_INDICATOR_FILES              59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32855
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
